### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Ishanoshada** [SuperStormer/pyasm#3]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pyasm", line 33, in <module>
    sys.exit(load_entry_point('pyasm==0.1', 'console_scripts', 'pyasm')())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyasm/__init__.py", line 240, in main
    print(pretty_decompile(f.read(), args.filename), file=o)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyasm/__init__.py", line 222, in pretty_decompile
    for name, code, arg_names in decompile(disasm, filename, version):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyasm/__init__.py", line 214, in decompile
    uncompyle6.main.decompile(version, code, out)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/main.py", line 140, in decompile
    deparsed = deparse_fn(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/semantics/pysource.py", line 2570, in code_deparse
    scanner = get_scanner(version, is_pypy=is_pypy)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/scanner.py", line 565, in get_scanner
    scanner = eval(
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/scanners/scanner39.py", line 36, in __init__
    Scanner37Base.__init__(self, 3.9, show_asm)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/scanners/scanner37base.py", line 98, in __init__
    self.opc.END_FINALLY,
AttributeError: module 'xdis.opcodes.opcode_39' has no attribute 'END_FINALLY'

**Comment by Ishanoshada** [comment]
K

**Comment by SuperStormer** [comment]
https://stackoverflow.com/help/minimal-reproducible-example
